"""
Module 9 — Claude Prompt Generator.

Converts an AnalysisResult into a ready-to-paste Claude Code prompt that a
developer can use to fix the identified UI issues in their codebase.
No API calls — pure text generation.
"""
from __future__ import annotations

from backend.models.analysis import AnalysisResult
from backend.models.issue import Severity


_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
    Severity.SUGGESTION: "⚪",
}


def generate(result: AnalysisResult) -> str:
    """Return a paste-ready Claude Code prompt from an AnalysisResult."""
    lines: list[str] = []

    lines.append("# UI/UX Improvement Task")
    lines.append("")
    lines.append(
        f"This UI scored **{result.overall_score}/100** in a UICopilot analysis. "
        f"Please fix the issues below, prioritised by impact."
    )
    lines.append("")

    # Category summary
    lines.append("## Category Scores")
    for cs in sorted(result.category_scores, key=lambda c: c.score):
        bar = "█" * int(cs.score / 10) + "░" * (10 - int(cs.score / 10))
        lines.append(f"- **{cs.category.value.replace('_', ' ').title()}**: {cs.score:.0f}/100 [{bar}]")
    lines.append("")

    # High-impact fixes
    if result.high_impact:
        lines.append("## High-Impact Fixes (do these first)")
        for i in result.high_impact:
            emoji = _SEVERITY_EMOJI.get(i.severity, "")
            lines.append("")
            lines.append(f"### {emoji} {i.rule_id}")
            lines.append(f"**Problem:** {i.message}")
            lines.append(f"**Fix:** {i.recommendation}")
            if i.why:
                lines.append(f"**Why it matters:** {i.why}")
            if i.references:
                lines.append(f"**Reference products:** {', '.join(i.references)}")
        lines.append("")

    # Quick wins
    if result.quick_wins:
        lines.append("## Quick Wins (under 15 minutes each)")
        for i in result.quick_wins:
            if i not in result.high_impact:
                lines.append(f"- **{i.rule_id}** ({i.estimated_time}): {i.recommendation}")
        lines.append("")

    # Accessibility — always list separately because they may be legally required
    a11y = [i for i in result.accessibility_fixes if i not in result.high_impact]
    if a11y:
        lines.append("## Accessibility Fixes (may be legally required)")
        for i in a11y:
            lines.append(f"- **{i.rule_id}** [{i.severity.value}]: {i.recommendation}")
        lines.append("")

    # Remaining issues
    remaining = [
        i for i in result.issues
        if i not in result.high_impact
        and i not in result.quick_wins
        and i not in result.accessibility_fixes
    ]
    if remaining:
        lines.append("## All Remaining Issues")
        for i in remaining:
            lines.append(f"- **{i.rule_id}** ({i.severity.value}): {i.message}")
        lines.append("")

    lines.append("---")
    lines.append(
        "_Generated by [UICopilot](https://github.com/yourusername/uicopilot). "
        "Paste this prompt into Claude Code and point it at your source files._"
    )

    return "\n".join(lines)
